* In Emergency

John Aspden 07943 155029  / 0114 2341378

James Howard 07988 843475
Emma  Howard 07989 444046

James Tidy 07724 056240
Amy        07828 763885

or just ask anyone on a boat nearby!

* Checklist
Keep Fire In / Internal temperature above 0
Keep Batteries Charged above 12.2volts/50%. 
Top up water/empty sewage if necessary. (Should last two weeks if you're careful)

* Major Threats
** Fire
*** setting light to boat
Careful not to leave anything flammable on or near the fire, or allow it to run out of control.  Don't leave boat without checking.
There are three fire extinguishers, notice where they are. 
*** chimney Fire
Can be caused if there's flammable layer inside stove pipe. Becomes blast furnace. Quite spectacular. 
Close all vents tight to reduce amount of air going in, and summon fire brigade. 

** Crashing
Hull is solid. You'd have to work quite hard to damage it. But...
Boat weighs 26tons. Even moving very slowly it will crush arms and legs between it and the bank. Hitting a plastic cruiser will shatter it.
Don't move it in strong stream or wind. Go slow and careful. Turn very gently and don't let it hit either bank as can break things inside.
** Gas Explosion
Boat Gas very dangerous, builds up in bilges. Careful not to leave gas on unlit, learn smell.
** Burst Pipes
Temperatures below zero will burst water pipes and calorifier, £1000 of damage, keep fire in if it's cold
** Flooding
When the water goes back down the boat must be in the river. If it sits on the bank it will overturn and sink. 
Once it's caught it's impossible to move it off because it weighs 26 tons.
Cure is scaffold poles. Currently lying in the grass. *Get help* if it starts to flood or rains heavily for a long time. 
Drive poles deep into river bed to keep boat where it is.
** Carbon Monoxide
Various detectors throughout boat. Fire shouldn't make CO unless banked very low. Levels below 30 ppm are not dangerous.
** Stern Gland
Remember to retighten grease injector every time prop has turned. Leaking stern gland and clogged pump/dead battery can sink boat.

* Minor Threats
** Discharged Batteries
Batteries in low charge state are damaged by it. If you notice voltage less than 12.2 unloaded / less than 50%, run engine until back to 80%/when charging stops
** Water Pump Burnout
If you run out of water, the pump will run continuously, which will burn it out. Switch off in fuse cupboard.
** Water Leak
Any water leak, turn off water pump and stopcock in left hand front cupboard.
** Sewage Tank
When full, toilet won't flush. Careful not to cause it to overflow, empty tank ASAP before anything gross happens.
** Burglars
Not much of a problem apparently, but I leave the bank side and front door curtains shut usually so that no-one can see in.
Don't leave hatch open when going out, since it's just about possible that someone will notice and climb round/over.

* Stove
Regulate heat by controlling amount of air allowed in. 
Unless trying to revive dead fire/lighting new one, have all vents closed and use the screw to control how much air can sneak in.
Keep top vents (for wood burning) and slider closed. Careful of slider, can open without you noticing.
Don't worry about how much coal you use. It's very cheap and I've got lots. Keep warm.
Screw settings
fully closed: fire may go out. don't use.
tau/8 / 45 degrees: fire will stay in for 12hours+, doesn't put out much heat. 
tau/4 / 90 degrees:  usual setting unless it's very cold
tau/2 / 180 degrees: fire will be very hot, but coal will all be used up in a few hours.

If you open the vents and go out or leave the front open for long you'll probably burn down the boat!

Careful not to spill hot ash, I've already made two holes in the carpet.

Ash goes into ash box, then empty into the bin on the common. Only once it's cold though, or it will set fire to the bin bags.
Suck up spilt dust with hoover. Don't use brush, it just makes it worse.

Should the fire go out, the easiest way to relight it is to riddle out all the dead ash, make a hole in the remaining coal, and then 
light a wood fire in the hole. That should relight the coal.

Very difficult to light wet coal directly. Get wood fire going and then top up with coal once everything's burning.

* Electricity
Powers everything. Enough from solar panels even in mid-winter to power systems, cabin lights, radio.
All others incandescents for warmer light. Don't leave them on too long as it drains batteries. 
If you'd like them on then there are LED replacements in the front left cupboard, but the light isn't as warm.

Fridge is huge consumer of electricity and mid winter it draws more power than the solar panels can provide.
You can make electricity by running the engine when the batteries are low.
Starter battery is separate circuit so even if the batteries are very low the engine should start.

* Lights
Front cabin lights are all LEDs. Draw very small amounts of power so can have them on for hours.

* Hot Water
Produced as side effect of running engine. But I find it easier to make small amounts in the kettle, and take showers elsewhere.

* Shower
I avoid using it in cold weather. It makes lots of condensation, runs down the water tank, and you need to heat the water first.
Boathouse showers more convenient in all ways. But feel free if you'd like to.

Run the engine for a half hour or so to make enough hot water (maybe go cruising or to the water point).
Turn on extractor fan and drain pump while showering (two different switches on wall near shower)

* Refilling with water
hex key handle opens water inlet in foredeck.
Clean the end of the hose before you put it anywhere near the fresh water tank. 
Careful not to get leaves/dirt etc in water tank as there's no way to get them out.

* Sewage pump-out
Do after water to avoid danger of contaminating fresh water tank.
Wear rubber gloves, hex key opens sewage tank on port side.
EA key opens sewage pump house at top of bank, where you put the money in.
Connect hose, close valve, insert £3, wait for pressure gauge to build up, open valve.
Sometimes no pressure. That means it's buggered. Phone council. They usually fix it quickly.

* Fuse cupboard
Usually have all switches on, except for bilge pump and nav lights (which must be off except when in use)
Turn everything off if leaving boat alone for a long time.
Main use is to disable water pump in event of running out of water, but you also lose the front sockets and radio on the same switch.

* Fridge
Uses loads of power, you'll need to run the engine occasionally if you want the fridge on. 
Its switch also controls the cabin wall lights so they won't work if the fridge is off.

* Inverter
Turns 12v into 240v, can be used for mobile chargers, laptops, although I have 12v versions. Main use is for DAB radio, although boat FM radio is better and uses less power.
The inverter draws power just by being on, so always switch it off when you've finished using it.







































