* In Emergency

John Aspden 07943 155029  / 0114 2341378

James Tidy 07724 056240 (local boat enthusiasts)
Amy        07828 763885

James Howard 07988 843475 (very competent rower/ex-boat pikey, sadly now lives on Tyneside)
Emma  Howard 07989 444046 

or just ask anyone on a boat nearby!

* Checklist
Keep Fire In / Internal temperature above 0
Keep Batteries Charged above 12.2volts/50%. 
Top up water/empty sewage if necessary. (Should last around two weeks if you're careful)

* Major Threats
** Fire
*** aboard
Careful not to leave anything flammable on or near the fire, or allow it to run out of control.  Don't leave boat without checking.
There are three fire extinguishers, notice where they are. CALL FIRE BRIGADE FIRST.
*** chimney fire
Can be caused if there's flammable layer inside stove pipe. Becomes blast furnace. Quite spectacular apparently.
Close all vents tight to reduce amount of air going in, and SUMMON FIRE BRIGADE. 
** Carbon Monoxide
Various detectors throughout boat. Fire shouldn't make CO unless banked very low. 
Levels below 30 ppm are not dangerous. But in high concentrations it's deadly, invisible and doesn't smell of anything.
** Gas Explosion
Boat Gas (propane) is very dangerous, heavier than air, so it builds up in bilges. 
Careful not to leave gas on unlit, learn smell, which is not the same as house gas.
** Burst Pipes
Temperatures below zero will burst water pipes and calorifier, £1000s of damage, keep fire in if it's cold
** Flooding
When the water goes back down the boat must be in the river. If it sits on the bank it will overturn and sink. 
Once it's caught it's impossible to move it off because it weighs 26 tons.
Cure is scaffold poles. Currently in position. *Get help* if it starts to flood or rains heavily for a long time. 
Drive poles deep into river bed to keep boat where it is.
** Crashing
Hull is solid. You'd have to work quite hard to damage it. But...
Boat weighs 26tons. Even moving very slowly it will crush arms and legs between it and the bank. Hitting a plastic cruiser will shatter it.
Don't move it in strong stream or wind. Go slow and careful. Turn very gently and don't let it hit either bank as can break things inside.
** Stern Gland
Remember to retighten grease injector every time prop has turned. Leaking stern gland and clogged pump/dead battery can sink boat.


* Minor Threats
** Toilet
*Never* put anything down a boat toilet that you haven't eaten. Carefully selected soft toilet paper is also ok.
Anything else will instantly jam the mechanism. Repair needs a plumber, extensive destruction and probably new parts.
** Discharged Batteries
   Batteries in low charge state are damaged by it. If you notice voltage less than 12.2 unloaded / less than 50%, run engine until back to 80%/when charging stops
   Engine needs throttle blipped gently to 'prime' alternator. If it's not going then the rev counter will be dead and the yellow battery light will be on. When alternator is running with engine idle it should be putting 20A into the batteries, and the battery meter should show this. If the initial throttle blip doesn't start it, leave the engine running gently for a few minutes and try again. I don't know why this is. Maybe there is damp in the alternator and it needs to warm up before it will start working?
** Water Pump Burnout
If you run out of water, the pump will run continuously, which will burn it out. Switch off in fuse cupboard.
** Water Leak
Any water leak, turn off water pump and stopcock in left hand front cupboard.
** Sewage Tank
When full, toilet won't flush. Careful not to cause it to overflow, empty tank ASAP before anything gross happens.
** Burglars
Not much of a problem apparently, but I leave the bank side and front door curtains shut usually so that no-one can see in. 
Don't leave hatch open when going out, since it's possible that someone will notice and climb round/over. It's easy to see from the bridge/other side of the river.

* Stove
** remove ash every time you put new coal on
Careful not to spill hot ash, I've already made two holes in the carpet.

The Guardian is exactly the right size to lay in front of the fire to keep ash off the floor when messing. When done, fold up the top sheet of paper and bin it.

Ash goes into ash box, then when cooled empty the box into the bin on the common. 
Only once it's cold though, or it will set fire to the bin bags.

Suck up spilt dust with hoover. Don't use brush, it just makes it worse.

** Normal usage 
If you open the vents and go out or leave the front open for long you'll burn down the boat!

Regulate heat by controlling amount of air allowed in. 
Unless trying to revive dead fire/lighting new one, have all vents closed and use the screw to control how much air can sneak in.
Keep top vents (for wood burning) and slider closed. Careful of slider, can open without you noticing.
Don't worry about how much coal you use. It's very cheap and I've got lots. Keep warm.

usual screw settings (roughly, depends how much ash is clogging it up)
fully closed: fire may go out. don't use.
tau/8 / 45 degrees: fire will stay in for 12hours+, doesn't put out much heat. 
tau/4 / 90 degrees:  usual setting unless it's very cold
tau/2 / 180 degrees: fire will be very hot, but coal will all be used up in a few hours.
** if fire is drawing too much air
It shouldn't do. It's properly sealed, but if it does you can:
Put a layer of ash on top of the burning coal to calm it down
Put cardboard strips in the ash pit vents to make a better seal

If it gets away from you, take everything flammable away from the fire, and put ash on top of the coal to form a blanket and calm it down. If it's looking dangerous or out of control CALL THE FIRE BRIGADE before anything dreadful happens.

** relighting if it goes out
Should the fire go out, don't remove the ash or unburnt coal. Make a little hole in the coal, put a firelighter in the hole and then put a couple of pieces of kindling wood on top to make a 'combustion chamber'. Light the firelighter, then put coal on top of the wood.

It's difficult to light wet coal directly. Make sure there's always some coal in the bucket drying out so you don't end up with a dead fire and only wet coal to light it with. If you find yourself with no dry coal then try the blue plastic bucket which is usually in the foredeck well or on the bank next to the boat.


* Electricity
Powers everything. Enough from solar panels even in mid-winter to power systems, cabin lights, radio.

Battery monitor on cupboard door at sleeping cabin end. 12.6 volt is fully charged, 12.2 is half-charged. Don't let it get that low.

Fridge is huge consumer of electricity and mid winter it draws more power than the solar panels can provide.
You can make more electricity by running the engine when the batteries are low. Wait until the engine is warmed up before revving it up with the neutral button pressed in to make the alternator work. RPM indicator will read zero unless alternator is generating electricity.

Starter battery is a separate circuit so even if the main batteries are very low the engine should start. A running alternator charges both.

* Lights
Front cabin lights are all LEDs. Draw very small amounts of power so can have them on for hours.
All others (including galley) are incandescents for warmer light. Don't leave them on too long as it drains batteries. 
If you'd like other lights on for a while, then there are LED replacements in the front left cupboard, but the light isn't as warm.

* Hot Water
Produced as side effect of running engine. But I find it easier to make small amounts in the kettle, and take showers elsewhere.

There's also a little eberspacher water heater which burns diesel to heat water. Run that for half an hour and you should have enough hot water for a shower. The eberspacher will only work if the battery voltage is high enough, so if it doesn't, run the engine to charge the batteries and that will also make hot water as it runs.

* Shower
I avoid using it in cold weather. It makes lots of condensation, runs down the water tank, and you need to heat the water first.
Boathouse showers more convenient in all ways. But feel free if you'd like to.

Run the engine or the eberspacher for a half hour or so to make enough hot water (maybe go cruising or to the water point).

Turn on extractor fan and drain pump while showering (two different switches on wall near shower)

* Refilling with water
hex key handle opens water inlet in foredeck.

I have a nice new hose on a reel and a separate endpiece to go in the water tank which makes it much easier than it used to be. 

CLEAN THE END OF THE HOSE BEFORE YOU PUT IT ANYWHERE NEAR THE FRESH WATER TANK. 
CAREFUL NOT TO GET LEAVES/DIRT ETC IN WATER TANK AS THERE'S NO WAY TO GET THEM OUT.

* Sewage pump-out
Do after water to avoid danger of contaminating fresh water tank.
Wear rubber gloves, hex key opens sewage tank on port side.
EA key opens sewage pump house at top of bank, where you put the money in.
Connect hose, close valve, insert £3, wait for pressure gauge to build up, open valve.

Sometimes there's no pressure. That means it's buggered. Phone council. They usually fix it quickly. 
Usually you can fix it yourself by sucking water out of the river which will clean the pipe and pump. It will suck sluggishly and then suddenly start working properly.

* Fuse cupboard
Usually have all switches on, except for bilge pump and nav lights (which must be off except when in use)
Turn everything off if leaving boat alone for a long time.
Main use is to disable water pump in event of running out of water, but you also lose the front sockets and radio on the same switch.

* Fridge
Uses loads of power, you'll need to run the engine occasionally if you want the fridge on. I don't use it in the Winter. If you put stuff on the back steps in cold months it won't go off in a hurry.

The fridge switch also controls the incandescent cabin wall lights so they won't work if the fridge is off. But you shouldn't put them on in winter anyway as they use far too much electricity.

* Inverter
Turns 12v into 240v, can be used for mobile chargers, laptops, although I have 12v versions. Main use is for DAB radio, although boat FM radio is better and uses less power.
The inverter draws power just by being on, so always switch it off when you've finished using it.







































