(defn tone[] (rand-nth ["tonic 2",
           "high 3->2","high 4->3->2", "high 5->4->3->2", "high 6->5->4->3->2", "high 7->6->5->4->3->2", "high 1->7->6->5->4->3->2","high 2->1->7->6->5->4->3->2",
                      "low 1->2","low 7->1->2", "low 6", "low 5", "low 4", "low 3","low 2"]))

(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone)
(tone) 
