#!/bin/bash

GUI=yes

cur=`pwd` 
echo saving directory $cur
for i in ~/hobby-code/ ~/data;
do
  echo ---------$i------------
  if [[ -d $i ]] ; then
      cd $i
      if [[ -z $1 ]] ; then 
          git status
      elif [ $1 = 'gui' ] ;
      then
          git gui
      elif [ $1 = 'pull' ] ;
      then
          git pull
      elif [ $1 = 'push' ] ;
      then
          git push
      else
          echo "unknown command $1"
      fi
  else
      echo --does not exist--
  fi
done

for i in ~/pyenv/src/ckan ~/pyenv/src/ckanext-admin ;
do
  echo ---------$i------------
  if [[ -d $i ]] ; then
      cd $i
      if [[ -z $1 ]] ; then 
          hg status
      elif [ $1 = 'gui' ] ;
      then
          hgtk commit
      elif [ $1 = 'pull' ] ;
      then
          hg pull
          hg update
      elif [ $1 = 'push' ] ;
      then
          hg push
      else
          echo "unknown command $1"
      fi
  else
      echo --does not exist--
  fi
done

echo ---------------------
echo returning to $cur
cd $cur
