(define (call-the-cops) (write "Call the cops!"))

(define (make-account amount secret-password)
  (define passwdtries 0)
  (define (badpasswdfn x)
    (set! passwdtries (+ passwdtries 1))
    (if (> passwdtries 3)
        (call-the-cops))
    "Incorrect Password")
  (define (withdrawfn x)
    (if (<= x amount)
        (begin
          (set! amount (- amount x))
          amount)
        "Insufficient Funds"))
  (define (depositfn x)
    (set! amount (+ amount x))
    "gracies")
  (define (balancefn)
    amount)
  (lambda (password operation)
    (if (equal? operation 'deposit) depositfn
        (if (equal? password secret-password)
            (cond ((equal? operation 'withdraw) withdrawfn)
                  ((equal? operation 'balance) amount)
                  (else error "Bad Operation: " operation))
            badpasswdfn))))

(define fluffy (make-account 100 'flaps))
(define oscar  (make-account 1000000 'p*ash-whsi8967))

((fluffy 'doom 'withdraw) 20)
((fluffy 'flaps 'withdraw) 20)
((fluffy 'placeholder 'deposit) 10)
((oscar  'a  'withdraw) 10000)
((fluffy 'flaps 'withdraw) 30)
((fluffy 'flaps 'withdraw) 60)
((oscar  'b 'withdraw) 10000000)
((oscar 'c 'deposit) 0.001)
((oscar 'c 'withdraw) 100000)
((oscar 'c 'withdraw) 10000)
((fluffy 'doom 'deposit) 20)
(fluffy 'doom 'balance)
(fluffy 'flaps 'balance)